//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist_VietripInsum_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTour
    {
        public string IdDetailTour { get; set; }
        public string IdTour { get; set; }
        public string IdHotel { get; set; }
        public string Describe { get; set; }
        public string IdVistLocat { get; set; }
        public string IdTrans { get; set; }
        public string Image { get; set; }
        public string InfoConcentrate { get; set; }
    
        public virtual Tour Tour { get; set; }
        public virtual Transport Transport { get; set; }
        public virtual VistLocation VistLocation { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
