//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist_VietripInsum_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailSchedule
    {
        public int stt { get; set; }
        public string idSchedule { get; set; }
        public string idVitsLocal { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual VistLocation VistLocation { get; set; }
    }
}
