//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist_VietripInsum_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaDiemThamQuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiaDiemThamQuan()
        {
            this.ChiTietTours = new HashSet<ChiTietTour>();
        }
    
        public string MaTinh { get; set; }
        public string MaDDTQ { get; set; }
        public string TenDDTQ { get; set; }
        public string MoTa { get; set; }
        public string DiaChi { get; set; }
        public string HinhMinhHoa_D { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTour> ChiTietTours { get; set; }
        public virtual TinhThanh TinhThanh { get; set; }
    }
}
