//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist_VietripInsum_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public string MaKS { get; set; }
        public string MaTinh { get; set; }
        public string TenKS { get; set; }
        public string Sao { get; set; }
    
        public virtual TinhThanh TinhThanh { get; set; }
    }
}
