//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist_VietripInsum_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderCu()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public string IdOrder { get; set; }
        public string IdCus { get; set; }
        public string IdStaff { get; set; }
        public string IdTour { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string StatusOrder { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string NumberPhone_Cus { get; set; }
    
        public virtual Customer_Guest Customer_Guest { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Tour Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
