//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist_VietripInsum_2023.Models
{
    using System;
    using System.Collections.Generic;
    using Tourist_VietripInsum_2023.DesignPattern.Prototype;

    public partial class PhuongTien : ITransportPrototype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhuongTien()
        {
            this.ChiTietTours = new HashSet<ChiTietTour>();
        }
    
        public string MaPTien { get; set; }
        public string TenPTien { get; set; }
        public string HangXe { get; set; }
        public string ChiTiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTour> ChiTietTours { get; set; }

        public ITransportPrototype Clone()
        {
            PhuongTien newPT = new PhuongTien();
            Random rd = new Random();
            var idTrans = "PTD" + rd.Next(10, 10000);
            newPT.MaPTien = idTrans;
            newPT.TenPTien = TenPTien;
            newPT.HangXe = HangXe;
            newPT.ChiTiet = ChiTiet;
            return newPT;
        }
    }
}
