//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist_VietripInsum_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.OrderCus = new HashSet<OrderCu>();
        }
    
        public string IdStaff { get; set; }
        public string IdPos { get; set; }
        public string Username { get; set; }
        public string UserPassword { get; set; }
        public string FullName { get; set; }
        public string NumberPhone { get; set; }
        public string StaffAddress { get; set; }
        public string StaffEmail { get; set; }
        public Nullable<System.DateTime> StaffBirthday { get; set; }
        public string Gender { get; set; }
        public string Avatar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCu> OrderCus { get; set; }
        public virtual Position Position { get; set; }
    }
}
