//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist_VietripInsum_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string IdTicket { get; set; }
        public string IdOrder { get; set; }
        public string IdTypeTicket { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
    
        public virtual OrderCu OrderCu { get; set; }
        public virtual TypeTicket TypeTicket { get; set; }
    }
}
