//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist_VietripInsum_2023.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.ChiTietTours = new HashSet<ChiTietTour>();
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public string IdTour { get; set; }
        public string Id_TypeTour { get; set; }
        public string ImagerTour { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<System.DateTime> ReturnDay { get; set; }
        public Nullable<int> TimeTour { get; set; }
        public string DeparturePlace { get; set; }
        public Nullable<int> NumberAvailable { get; set; }
        public Nullable<decimal> PriceChildren { get; set; }
        public Nullable<decimal> PriceAdult { get; set; }
        public Nullable<System.DateTime> DeadlineOrder { get; set; }
        public string TourName { get; set; }
        public string Destination { get; set; }
        public string Mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTour> ChiTietTours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual LoaiTour LoaiTour { get; set; }
    }
}
