//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist_VietripInsum_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.OrderCus = new HashSet<OrderCu>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public string IdTour { get; set; }
        public string Id_TypeTour { get; set; }
        public string Id_detailTour { get; set; }
        public string ImagerTour { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<System.DateTime> ReturnDay { get; set; }
        public Nullable<int> TimeTour { get; set; }
        public string DeparturePlace { get; set; }
        public Nullable<int> NumberAvailable { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> DeadlineOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCu> OrderCus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual TourType TourType { get; set; }
    }
}
